services:
  ###############################
  # FRONTEND (Vue)
  ###############################
  frontend:
    build: ./front-pjt/travel-front
    container_name: travel-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front-pjt/travel-front:/app
      - /app/node_modules
    networks:
      - travel-net

  ###############################
  # BACKEND (Django)
  ###############################
  backend:
    build: ./backend-pjt
    container_name: travel-backend
    volumes:
      - ./backend-pjt:/app
      - ./backend-pjt/dummy_data:/data          # ⭐ CSV seed 데이터
    # backend는 db가 켜진 뒤에 실행해야 하므로 dependencies 선언.
    # 완전히 기다리지는 않지만 순서 보장됨
    depends_on:
      - db
      - kafka
    # Django가 DB에 접속할 때 필요한 환경 변수들 전달
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST} # Backend 컨테이너는 DB 컨테이너에 서비스 이름(db)으로 접속함
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    networks:
      - travel-net

  ###############################
  # DB (postgre)
  ###############################
  db:
    image: postgres:16
    container_name: travellens-db
    # 컨테이너가 죽어도 자동 재시작 -> 서버 운영 시 매우 중요
    restart: unless-stopped
    environment:
      # 생성할 기본 데이터 베잉스 이름
      POSTGRES_DB: ${POSTGRES_DB}
      # 관리자 계정
      POSTGRES_USER: ${POSTGRES_USER}
      # 비밀번호
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # 타임존 설정(한국 표준시)
      TZ: Asia/Seoul
    # Postgres의 실제 데이터 파일은 /var/lib/postgresql/data에 저장
    # 이를 도커 볼륨(postgres-data)에 연결 -> 컨테이너가 삭제되어도 데이터 유지됨
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # 호스트 PC 포트 5432 -> 컨테이너 포트 5432 연결
    # 로컬 툴(DBeaver, PgAdmin 등)로 접속할 때 필요
    ports:
      - "5432:5432"
    networks:
      - travel-net

  ###############################
  # Zookeeper 
  ###############################
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - travel-net


  ###############################
  # kafka
  ###############################
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092" # docker 내부용
      - "29092:29092" # docker 외부 (호스트(WSL/Windows)에서 접속)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
    networks:
      - travel-net

  ###############################
  # Flink JobManager
  ###############################
  flink-jobmanager:
    build: ./data-pipeline/flink
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./data-pipeline/flink/jobs:/jobs
    depends_on:
      - kafka    
    networks:
      - travel-net

  ###############################
  # Flink TaskManager
  ###############################
  flink-taskmanager:
    build: ./data-pipeline/flink
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
      - kafka
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4
    networks:
      - travel-net

volumes:
  postgres-data:

networks:
  travel-net:
    driver: bridge