input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/plugins/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
  jdbc_user => "${POSTGRES_USER}"
  jdbc_password => "${POSTGRES_PASSWORD}"


    statement => "
      SELECT
        id,
        title,
        url,
        published_at,
        iso2,
        updated_at
      FROM destination_blog
      WHERE updated_at > :sql_last_value
    "

    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"
    schedule => "*/3 * * * *"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "blog_index"
    document_id => "%{id}"
  }
}
