input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/plugins/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    jdbc_user => "${POSTGRES_USER}"
    jdbc_password => "${POSTGRES_PASSWORD}"


    statement => "
      SELECT
        iso2,
        iso3,
        name_ko,
        name_en,
        continent_name_ko,
        continent_name_en
      FROM country
    "

    add_field => { "source_type" => "country" }
    clean_run => true
    schedule => "*/5 * * * *"
  }
}

output {
  if [source_type] == "country" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "country_index"
      document_id => "%{iso2}"
    }
  }
}
